### ISSUE TITLE
Adding multi selected cuties to a group resets level filter ui but filter is still applied

### ISSUE THREAD

**Issue by viracocha48** [klesun/bcu-bugs-public#16] opened 2021-10-25 02:24 UTC
When selecting cuties and adding them to a group while a level filter is applied, the UI resets but the filter is still being applied, visible in the GET parameters.

![image](https://user-images.githubusercontent.com/89263929/138606091-3084e779-752d-4d82-97e2-ea9bc3461368.png)
![image](https://user-images.githubusercontent.com/89263929/138606120-f34eb83b-6d39-4a82-9c13-8ec74ebbf6c9.png)
![image](https://user-images.githubusercontent.com/89263929/138606054-bd6c7c18-4106-4d1f-9c9c-4d5d7ae7251b.png)
![image](https://user-images.githubusercontent.com/89263929/138606063-e1ea46b6-c7c3-499a-a9d8-235eebb61fa1.png)

As you can see, the parameter is still there and being used, but not showing in the level selector.
![image](https://user-images.githubusercontent.com/89263929/138606164-3cde33c2-ea57-4a14-983a-7109d520ed8c.png)
![image](https://user-images.githubusercontent.com/89263929/138606178-8ce882b1-9ef9-4d09-ba15-903908334510.png)

**Comment by QAteamMember** [comment] 2022-02-02 20:43
@viracocha48 Thank you for this report. The issue is not reproducible anymore.

**Comment by klesun** [comment] 2022-02-02 20:46
Please let us know if we misunderstood something and the issue is still happens for you. Assuming that we understood everything right, I'm closing the ticket for now.

**Closed as completed by klesun** 2022-02-02 20:46 UTC

**Comment by klesun** [comment] 2022-02-02 21:12
It was probably fixed in BC-2973, release 21.11.5.1

**Comment by viracocha48** [comment] 2022-02-06 01:14
It does appear to have been fixed. Thanks!
